apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: webapp
 name: webapp
spec:
 replicas: 1
 selector:
   matchLabels:
     app: webapp
 template:
   metadata:
     labels:
       app: webapp
   spec:
    containers:
    - image: ghcr.io/kevin-jones/gitops-example/nginx:latest
      name: nginx
      volumeMounts:
      - mountPath: /etc/nginx/conf.d
        name: nginx-config
    - image: ghcr.io/kevin-jones/gitops-example/php:latest
      name: php