apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: gitopsexample
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
  - name: nginx80
    protocol: TCP
    port: 80
    targetPort: 80