on: [push]
jobs:
  cleanse:
    runs-on: ubuntu-latest
    steps:
      - name: Delete NGINX Package Versions
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'gitops-example/nginx'
          package-type: 'container'
          min-versions-to-keep: 3
      - name: Delete PHP Package Versions
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'gitops-example/php'
          package-type: 'container'
          min-versions-to-keep: 3
